//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_FRAMEWORK_LIBROS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libros
    {
        [Display(Name = "#")]
        public int ID { get; set; }
        [Display(Name = "Titulo del libro")]
        public string Titulo { get; set; }
        [Display(Name = "Autor del libro")]
        public string Autor { get; set; }
        [Display(Name = "Año de publicacion")]
        public Nullable<int> AñoPublicacion { get; set; }
    }
}
